export { default as ArrowDownIcon } from './ArrowDownIcon';
export { default as ArrowRightIcon } from './ArrowRightIcon';
export { default as ArrowLeftIcon } from './ArrowLeftIcon';
export { default as CheckIcon } from './CheckIcon';
export { default as SearchIcon } from './SearchIcon';
export { default as LoaderIcon } from './LoaderIcon';
export { default as GithubIcon } from './GithubIcon';
export { default as StarIcon } from './StarIcon';
export { default as LinkIcon } from './LinkIcon';
export { default as EyeIcon } from './EyeIcon';
export { default as ForkIcon } from './ForkIcon';
export * from './Icon';
